syntax = "proto3";

package auth;

option go_package = "example.com/proto/auth";

service Auth {
    rpc Authorize (AuthorizeRequest) returns (AuthorizeResponse) {}

    rpc ExtractUserId (ExtractUserIdRequest) returns (ExtractUserIdResponse) {}

    rpc GetLogin (GetLoginRequest) returns (GetLoginResponse) {}
}

message AuthorizeRequest {
    reserved 1,2,3,4;
}

message AuthorizeResponse {
    reserved 1,2,3,4;
}

message ExtractUserIdRequest {}

message ExtractUserIdResponse {
    string userId = 1;
}

message GetLoginRequest {
    string userId = 1;
}

message GetLoginResponse {
    string login = 1;
}