syntax = "proto3";

package chat;

option go_package = "example.com/proto/chat";

service Chat {
    rpc GetChat (GetChatRequest) returns (ChatResponse) {}

    rpc VerifyUserAction (VerifyUserActionRequest) returns (VerifyUserActionResponse) {}
}

message ChatResponse {
    string chatId = 1;
    string name = 2;
    string description = 3;
    string profilePic = 4;
    bool isChannel = 5;
    bool isClosed = 6;
    string joinLink = 7;
    string creatorId = 8;
    repeated string participantsIds = 9;
}

message GetChatRequest {
    string chatId = 1;
    string userId = 2;
}

message VerifyUserActionRequest {
    string chatId = 1;
    string userId = 2;
    string action = 3;
}

message VerifyUserActionResponse {
    bool isVerified = 1;
}