services:
  messaging_app:
    build:
      context: .
      dockerfile: app.Dockerfile
    container_name: messaging_app
    ports:
      - "${APP_HTTP_PORT}:${APP_HTTP_INNER_PORT}"
    environment:
      - DB_HOST=messaging_db
      - DB_PORT=${DB_INNER_PORT}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_INNER_PORT}
      - AUTH_HOST=auth_app
      - AUTH_PORT=${AUTH_INNER_PORT}
      - CHAT_HOST=chat_app
      - CHAT_PORT=${CHAT_INNER_PORT}
      - APP_HTTP_PORT=${APP_HTTP_INNER_PORT}
    depends_on:
      - messaging_db
    networks:
      - micro-proxy-net

  messaging_db:
    image: postgres:15.3
    container_name: messaging_db
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - micro-proxy-net

networks:
  micro-proxy-net:
    external: true
    name: microservice-network