services:
  media_app:
    build:
      context: .
      dockerfile: app.Dockerfile
    container_name: media_app
    ports:
      - "${APP_HTTP_PORT}:${APP_HTTP_INNER_PORT}"
    environment:
      - DB_HOST=media_db
      - DB_PORT=${DB_INNER_PORT}
      - AUTH_HOST=auth_app
      - AUTH_PORT=${AUTH_INNER_PORT}
      - SEAWEEDFS_MASTER_HOST=seaweedfs_master
      - SEAWEEDFS_MASTER_PORT=${SEAWEEDFS_MASTER_INNER_PORT}
      - APP_HTTP_PORT=${APP_HTTP_INNER_PORT}
    depends_on:
      - media_db
      - seaweedfs_master
    networks:
      - micro-proxy-net

  media_db:
    image: postgres:15.3
    container_name: media_db
    ports:
      - "${DB_PORT}:${DB_INNER_PORT}"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - micro-proxy-net

  seaweedfs_master:
    image: chrislusf/seaweedfs:latest
    container_name: seaweedfs_master
    ports:
      - "${SEAWEEDFS_MASTER_PORT}:${SEAWEEDFS_MASTER_INNER_PORT}"
    networks:
      - micro-proxy-net
    command: "master -ip=seaweedfs_master"

  seaweedfs_volume1:
    image: chrislusf/seaweedfs:latest
    container_name: seaweedfs_volume1
    ports:
      - "10000:8080"
    networks:
      - micro-proxy-net
    command: 'volume -mserver="seaweedfs_master:9333" -port=8080'
    depends_on:
      - seaweedfs_master

  seaweedfs_volume2:
    image: chrislusf/seaweedfs:latest
    container_name: seaweedfs_volume2
    ports:
      - "10001:8080"
    networks:
      - micro-proxy-net
    command: 'volume -mserver="seaweedfs_master:9333" -port=8080'
    depends_on:
      - seaweedfs_master

networks:
  micro-proxy-net:
    external: true
    name: microservice-network